lilo added for post install, sharedfunc
- updated readme added some TODOs
- added sharedfuncs from helmuthdu/aui
- added lilo script which will allow user to install kodi

diff --git a/fifo b/fifo
--- a/fifo
+++ b/fifo
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 # fifo.sh -- Sets up initial Archlinux environment on the specified
 # device.
@@ -27,11 +27,32 @@
 
 set -exu
 
+if [[ -f `pwd`/sharedfuncs ]]; then
+  source sharedfuncs
+else
+  echo "missing file: sharedfuncs"
+  exit 1
+fi
+
 DEV=$1
 WIFI_SSID=$2
 WIFI_PASS=$3
 
 cd $(mktemp -d)
+
+function welcome () {
+  clear
+  echo -e "${Bold}Raspberri Pi Archlinux Ultimate Install${White}"
+}
+
+function choose_editor () {
+
+}
+
+function configure_hostname () {
+  read -p "Hostname (archlinux): " host_name
+  echo "$host_name" > root/etc/hostname
+}
 
 function umountboot {
     umount boot || true
